### ISSUE TITLE
unable to render template

### ISSUE THREAD

**Issue by chen23** [f5devcentral/f5-fast-core#2]
getting the following error
```
$ node_modules/.bin/fast render openshift.mst params.json
/home/erchen/projects/fast/node_modules/yargs/yargs.js:1242
      else throw err
           ^

TypeError: Cannot read property 'readFile' of undefined
...
```
openshift.mst:
```
{
    "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
    "class": "AS3",
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.17.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "Common": {
            "class": "Tenant",
            "Shared": {
                "class": "Application",
                "template": "shared",
                "SharedVIP": {
                    "class": "Service_Address",
                    "virtualAddress": "{{virtual_address}}"
                },
                "XFF_HTTP_Profile": {
                    "class": "HTTP_Profile",
                    "xForwardedFor": true
                },
                "DataCenterOne": {
                    "class": "GSLB_Data_Center"
                },
                "OCPDNS": {
                    "class": "GSLB_Server",
                    "dataCenter": {
                        "use": "DataCenterOne"
                    },
                    "devices": [
                        {
                            "address": "{{ self_address }}",
                            "addressTranslation": "{{ self_address }}"
                        }
                    ],
                    "virtualServers": [
                        {
                            "address": "{{virtual_address}}",
                            "addressTranslation": "{{virtual_address}}",
                            "addressTranslationPort": 443,
                            "port": 443
                        },
                        {
                            "address": "{{virtual_address}}0",
                            "addressTranslation": "{{virtual_address}}0",
                            "addressTranslationPort": 80,
                            "port": 80
                        },
                        {
                            "address": "{{virtual_address}}1",
                            "addressTranslation": "{{virtual_address}}1",
                            "addressTranslationPort": 80,
                            "port": 80
                        },
                        {
                            "address": "{{virtual_address}}2",
                            "addressTranslation": "{{virtual_address}}2",
                            "addressTranslationPort": 80,
                            "port": 80
                        },
                        {
                            "address": "{{virtual_address}}",
                            "addressTranslation": "{{virtual_address}}",
                            "addressTranslationPort": 80,
                            "port": 80
                        }
                    ]
                }
            }
        },
        "OpenShiftInfra": {
            "class": "Tenant",
            "lb-ocp4-3-api": {
                "class": "Application",
                "template": "generic",
                "frontend-openshift-router": {
                    "class": "Service_TCP",
                    "remark": "openshift-router",
                    "virtualPort": 443,
                    "virtualAddresses": [
                        {
                            "use": "/Common/Shared/SharedVIP"
                        }
                    ],
                    "persistenceMethods": [
                        "source-address"
                    ],
                    "pool": "backend-openshift-router"
                },
                "backend-openshift-router": {
                    "class": "Pool",
                    "monitors": [
                        "tcp"
                    ],
                    "members": [
                        {
                            "servicePort": 443,
                            "serverAddresses": [
                                "{{ worker_address }}"
                            ],
                            "shareNodes": true
                        }
                    ]
                },
                "frontend-openshift-api-server": {
                    "class": "Service_TCP",
                    "remark": "openshift-api-server",
                    "virtualPort": 6443,
                    "virtualAddresses": [
                        {
                            "use": "/Common/Shared/SharedVIP"
                        }
                    ],
                    "persistenceMethods": [
                        "source-address"
                    ],
                    "pool": "backend-openshift-api-server"
                },
                "backend-openshift-api-server": {
                    "class": "Pool",
                    "monitors": [
                        "tcp"
                    ],
                    "members": [
                        {
                            "servicePort": 6443,
                            "serverAddresses":
                            ["{{ bootstrap_address }}", "{{ master_address}}"]
                            ,
                            "shareNodes": true
                        }
                    ]
                },
                "frontend-machine-config-server": {
                    "class": "Service_TCP",
                    "remark": "machine-config-server",
                    "virtualPort": 22623,
                    "virtualAddresses": [
                        {
                            "use": "/Common/Shared/SharedVIP"
                        }
                    ],
                    "persistenceMethods": [
                        "source-address"
                    ],
                    "pool": "backend-machine-config-server"
                },
                "backend-machine-config-server": {
                    "class": "Pool",
                    "monitors": [
                        "tcp"
                    ],
                    "members": [
                        {
                            "servicePort": 22623,
                            "serverAddresses": ["{{ bootstrap_address }}", "{{ master_address}}"],
                            "shareNodes": true
                        }
                    ]
                }
            }
        },
        "OpenShiftDNS": {
            "class": "Tenant",
            "OpenShift": {
                "class": "Application",
                "template": "generic",
                "dns_cache": {
                    "class": "DNS_Cache",
                    "type": "transparent",
                    "localZones": {
                        "api.dc1.example.com": {
                            "class": "DNS_Zone_Local",
                            "type": "static",
                            "records": [
                                "api.dc1.example.com. IN A {{virtual_address}}"
                            ]
                        },
                        "api-int.dc1.example.com": {
                            "class": "DNS_Zone_Local",
                            "type": "static",
                            "records": [
                                "api-int.dc1.example.com. IN A {{virtual_address}}"
                            ]
                        },
                        "bootstrap.dc1.example.com": {
                            "class": "DNS_Zone_Local",
                            "type": "static",
                            "records": [
                                "bootstrap.dc1.example.com. IN A {{bootstrap_address}}"
                            ]
                        },
                        "master.dc1.example.com": {
                            "class": "DNS_Zone_Local",
                            "type": "static",
                            "records": [
                                "master.dc1.example.com. IN A {{master_address}}"
                            ]
                        },
                        "worker-0.dc1.example.com": {
                            "class": "DNS_Zone_Local",
                            "type": "static",
                            "records": [
                                "worker-0.dc1.example.com. IN A {{worker_address}}"
                            ]
                        }
                    }
                },
                "dns_profile": {
                    "class": "DNS_Profile",
                    "cacheEnabled": true,
                    "cache": {
                        "use": "dns_cache"
                    }
                },
                "dns_listener_udp_vs": {
                    "class": "Service_UDP",
                    "virtualAddresses": [
                        {
                            "use": "/Common/Shared/SharedVIP"
                        }
                    ],
                    "virtualPort": 53,
                    "profileDNS": {
                        "use": "dns_profile"
                    },
                    "pool": "dns_resolver_pool"
                },
                "dns_listener_tcp_vs": {
                    "class": "Service_TCP",
                    "virtualAddresses": [
                        {
                            "use": "/Common/Shared/SharedVIP"
                        }
                    ],
                    "virtualPort": 53,
                    "profileDNS": {
                        "use": "dns_profile"
                    },
                    "pool": "dns_resolver_pool"
                },
                "dns_resolver_pool": {
                    "class": "Pool",
                    "monitors": [
                        "icmp"
                    ],
                    "members": [
                        {
                            "servicePort": 53,
                            "serverAddresses": [
                                "{{ external_dns_address }}"
                            ]
                        }
                    ]
                },
                "dns01_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/Shared/OCPDNS"
                            },
                            "virtualServer": "0"
                        }
                    ],
                    "resourceRecordType": "A"
                },
                "dns01_Domain": {
                    "class": "GSLB_Domain",
                    "domainName": "*.apps.{{ base_domain }}",
                    "resourceRecordType": "A",
                    "pools": [
                        {
                            "use": "dns01_pool"
                        }
                    ]
                },
                "dns02_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/Shared/OCPDNS"
                            },
                            "virtualServer": "1"
                        }
                    ],
                    "resourceRecordType": "A"
                },
                "dns02_Domain": {
                    "class": "GSLB_Domain",
                    "domainName": "*.cisroutes.{{ base_domain }}",
                    "resourceRecordType": "A",
                    "pools": [
                        {
                            "use": "dns02_pool"
                        }
                    ]
                },
                "dns03_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/Shared/OCPDNS"
                            },
                            "virtualServer": "2"
                        }
                    ],
                    "resourceRecordType": "A"
                },
                "dns03_Domain": {
                    "class": "GSLB_Domain",
                    "domainName": "my-frontend2.{{ base_domain }}",
                    "resourceRecordType": "A",
                    "pools": [
                        {
                            "use": "dns03_pool"
                        }
                    ]
                },
                "dns04_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/Shared/OCPDNS"
                            },
                            "virtualServer": "3"
                        }
                    ],
                    "resourceRecordType": "A"
                },
                "dns04_Domain": {
                    "class": "GSLB_Domain",
                    "domainName": "*.ingress.{{ base_domain }}",
                    "resourceRecordType": "A",
                    "pools": [
                        {
                            "use": "dns04_pool"
                        }
                    ]
                },
                "dns05_pool": {
                    "class": "GSLB_Pool",
                    "members": [
                        {
                            "ratio": 10,
                            "server": {
                                "use": "/Common/Shared/OCPDNS"
                            },
                            "virtualServer": "4"
                        }
                    ],
                    "resourceRecordType": "A",
                    "monitors": [
                        {
                            "use": "dns05_monitor"
                        }
                    ]
                },
                "dns05_monitor": {
                    "class": "GSLB_Monitor",
                    "monitorType": "http",
                    "send": "GET /txt HTTP/1.1\r\nhost: www.apps.{{ base_domain }}\r\nconnection: close\r\n\r\n",
                    "receive": "www"
                },
                "dns05_Domain": {
                    "class": "GSLB_Domain",
                    "domainName": "www.apps.{{ base_domain }}",
                    "resourceRecordType": "A",
                    "pools": [
                        {
                            "use": "dns05_pool"
                        }
                    ]
                }
            }
        }
    }
}

```
params.json
```
{
    "base_domain":"dc1.example.com",
    "self_address":"192.168.1.201",
    "virtual_address":"192.168.131.10",
    "bootstrap_address":"192.168.131.11",
    "master_address":"192.168.131.12",
    "worker_address":"192.168.131.13",
    "external_dns_address":"192.168.1.1"
}
```

**Comment by mstokes-f5** [comment]
This is rendering for me using `v0.5.1` and the latest `develop`. Are you using the latest release (v0.5.1)? If not, could you please try it out and see if it solves the problem for you?

**Comment by chen23** [comment]
here's what i'm running
```
    "@f5devcentral/f5-fast-core": {
      "version": "0.5.1",
      "resolved": "https://registry.npmjs.org/@f5devcentral/f5-fast-core/-/f5-fast-core-0.5.1.tgz",
      "integrity": "sha512-zfGxae8qmVxso/VirVM0oUzsu7/LoRECIAiz7RhJfwE0YIHmduvuPbPDW+i6uwbsImqyHz+1KAa45fRZLCTR+A==",
      "requires": {
        "@apidevtools/json-schema-ref-parser": "^9.0.1",
        "@f5devcentral/atg-storage": "^0.1.0",
        "ajv": "^6.12.2",
        "archiver": "^4.0.1",
        "deepmerge": "^4.2.2",
        "js-yaml": "^3.14.0",
        "mustache": "^4.0.1",
        "uuid": "^7.0.3",
        "yargs": "^15.3.1"
      }
    },
```
version
```
$ node --version
v8.12.0
```
output
```
$ node_modules/.bin/fast render issue.mst params.json
/home/erchen/projects/fast/node_modules/yargs/yargs.js:1242
      else throw err
           ^

TypeError: Cannot read property 'readFile' of undefined
    at loadParameters (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:33:15)
    at loadTemplateAndParameters (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:43:5)
    at renderTemplate (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:78:58)
    at Object.require.command.command.command.command.argv [as handler] (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:153:16)
    at Object.runCommand (/home/erchen/projects/fast/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/erchen/projects/fast/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/home/erchen/projects/fast/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/home/erchen/projects/fast/node_modules/@f5devcentral/f5-fast-core/cli.js:181:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

**Comment by mstokes-f5** [comment]
Node 8 is not an [active Node version](https://nodejs.org/en/about/releases/) and has reached "end-of-life" status. I suspsect that Yargs no longer supports it, but I cannot find any minimum Node requirements for Yargs. Could you please try a newer, supported version of Node?

**Comment by chen23** [comment]
works with v14.4.0.  looks like v8.12.0 is the LTS release

**Comment by chen23** [comment]
NM.  yes, v8.12.0 is old

**Comment by mstokes-f5** [comment]
Great to hear it is working for you with a newer Node version! I am closing this issue since we currently have no intention of supporting Node 8.
